name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rescoss_logp_ml
          environment-file: env.yml
          python-version: 3.8.13
          auto-activate-base: false
      - run: |
          conda info
          pip install pytest pytest-cov
        name: set pythonpath
      - run: |
          echo "PYTHONPATH=/home/runner/work/rescoss_logp_ml/rescoss_logp_ml" >> $GITHUB_ENV
        name: setup
      - run: |
          make saved_models
          make prepare_data
          curl -Os https://uploader.codecov.io/latest/linux/codecov 
          chmod +x codecov
          ./codecov
        name: test
      - run: |
          pytest --cov=rescoss_logp_ml --cov-config=.coveragerc --cov-report=xml tests/
          ./codecov -t ${{ secrets.CODECOV_TOKEN }} -W ignore::DeprecationWarning -W ignore::FutureWarning